### ISSUE TITLE
gives error when run in browsers other than chrome?

### ISSUE THREAD

**Issue by increpare** [spite/unmute#4]
even though I haven't figured out how to get it to work yet, it seems this needs dealing with?

```
[Error] ReferenceError: Can't find variable: chrome
	Globaler Code (background.js:4)
```

**Comment by spite** [comment]
it's for chrome only. chrome is the only implementing this autoplay policy

**Comment by increpare** [comment]
It's politer if libraries don't unnecessarily throw errors.  This is designed to fix a problem in chrome, but other browsers will also be loading the same pages.

**Comment by increpare** [comment]
ah, with the readme updated, I see that I totally misunderstood what this is for. cool!

**Comment by spite** [comment]
yes, it's not a library, it's a chrome extension

**Comment by eviltek2099** [comment]
why was this closed? i don't see a solution here??? I'm having this issue on a web site I'm making on chrome mobile. I need a way to check for the existence of a extension on our site!

**Comment by spite** [comment]
- it was closed because it was solved
- you don't see a solution because there wasn't a problem
- oh, too bad. check the autoplay policy changes https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
- wat

**Comment by eviltek2099** [comment]
I'm not trying to auto play. I developing a proctoring solution that i need to use "chrome.runtime.sendMessage" and I thought that doing `var c = chrome || undefined;` or `if (chrome)` would skip if chrome wasn't defined. works fine on all browsers except chrome on mobile. 
also, thanks for that really quick reply. wasn't expected ;) 
and sorry. been trying to fix this for 3 days now. no where can I find proper way to detect "is extension is installed and available"

**Comment by spite** [comment]
you probably can't use the extensions API because chrome for android doesn't support extensions. 
to detect if an extension is available: if extensions are supported and it's your extension, you can add a global flag to check. if it's not your extension, you don't really have many options

**Comment by eviltek2099** [comment]
Thank you very much, Its mine.  I am still learning this technology . global flag? please tell me more. Been doing lots of reading and I thought sendMessage was the only way to communicate between extension and tab?

**Comment by mqshen** [comment]
you can use 

```javascript
    if (typeof chrome === 'undefined') 
````

check if variable exists.
